"""empty message

Revision ID: 1619bb342b99
Revises: e3394ceb28af
Create Date: 2021-08-18 16:07:33.811392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1619bb342b99'
down_revision = 'e3394ceb28af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('events', 'day')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('day', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('events', 'description')
    # ### end Alembic commands ###
